Repository awslabs/amazon-kinesis-video-streams-webrtc-sdk-c, pull requests merged in 2024-11, with the labels that each got.

#2071 Add job to run the sample and check for memory leak
  .github/workflows/ci.yml
Labels: CI

#2074 Memory Optimization - ICE Agent Stats (#1947)
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  samples/Common.c
  samples/Samples.h
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/source/Ice/IceAgent.c
  src/source/Ice/IceAgent.h
  src/source/Metrics/Metrics.c
  tst/MetricsApiTest.cpp
Labels: memory-optimization

#2075 Memory Optimization - Refactor TWCC (#1934)
  src/source/PeerConnection/PeerConnection.c
  src/source/PeerConnection/PeerConnection.h
  src/source/PeerConnection/Rtcp.c
  src/source/PeerConnection/Rtcp.h
  src/source/PeerConnection/SessionDescription.h
  tst/RtcpFunctionalityTest.cpp
Labels: memory-optimization

#2079 Shorten Stats String Lengths
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
  src/source/Ice/IceAgent.h
Labels: memory-optimization

#2077 Memory Optimization - Rolling Buffer
  CMakeLists.txt
  README.md
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/source/Crypto/Dtls_mbedtls.c
  src/source/Crypto/Tls_mbedtls.c
  src/source/PeerConnection/PeerConnection.c
  src/source/PeerConnection/Rtp.c
  src/source/PeerConnection/Rtp.h
  src/source/PeerConnection/SessionDescription.c
  tst/DtlsFunctionalityTest.cpp
  tst/RtcpFunctionalityTest.cpp
  tst/RtpFunctionalityTest.cpp
  tst/RtpRollingBufferFunctionalityTest.cpp
  tst/SdpApiTest.cpp
Labels: memory-optimization, v1.11.1

#2073 Add option to specify stack size to pthread_create
  .github/workflows/ci.yml
  CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
  CMakeLists.txt
  README.md
Labels: memory-optimization, v1.11.1

#2082 SDP Attribute Fixes
  src/source/PeerConnection/SessionDescription.c
  tst/SdpApiTest.cpp
Labels: bug, v1.11.1

#2083 ReadMe Fixes
  README.md
Labels: documentation, v1.11.1
