Repository awslabs/amazon-kinesis-video-streams-webrtc-sdk-c, pull requests merged in 2024-12, with the labels that each got.

#2090 Upgrade to macos-13 and 15, use DRY for Mac jobs
  .github/workflows/ci.yml
Labels: CI, v1.11.1

#2089 Samples: Fit the RTP transceiver rolling buffers to fit the set of sample frames
  samples/Common.c
  samples/Samples.h
  samples/kvsWebRTCClientMaster.c
Labels: memory-optimization, Samples, v1.11.1

#2092 Bump the version from 1.11.1 to 1.12.0
  CMakeLists.txt
Labels: v1.11.1

#2093 Specify `configureTransceiverRollingBuffer` as a Public API
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
Labels: v1.12.0

#2087 v1.12.0 Release
  .github/workflows/ci.yml
  .github/workflows/pr-desc-lint.yml
  CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
  CMakeLists.txt
  README.md
  samples/Common.c
  samples/Samples.h
  samples/kvsWebRTCClientMaster.c
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
  src/source/Crypto/Dtls_mbedtls.c
  src/source/Crypto/Tls_mbedtls.c
  src/source/Ice/IceAgent.c
  src/source/Ice/IceAgent.h
  src/source/Metrics/Metrics.c
  src/source/PeerConnection/PeerConnection.c
  src/source/PeerConnection/PeerConnection.h
  src/source/PeerConnection/Rtcp.c
  src/source/PeerConnection/Rtcp.h
  src/source/PeerConnection/Rtp.c
  src/source/PeerConnection/Rtp.h
  src/source/PeerConnection/SessionDescription.c
  src/source/PeerConnection/SessionDescription.h
  src/source/Sdp/Deserialize.c
  tst/DtlsFunctionalityTest.cpp
  tst/MetricsApiTest.cpp
  tst/RtcpFunctionalityTest.cpp
  tst/RtpFunctionalityTest.cpp
  tst/RtpRollingBufferFunctionalityTest.cpp
  tst/SdpApiTest.cpp
Labels: Release, v1.12.0
