Repository awslabs/amazon-kinesis-video-streams-webrtc-sdk-c, pull requests merged in 2024-03, with the labels that each got.

#1943 Contributions target branch
  CONTRIBUTING.md
Labels: documentation

#1924 Thread stack sizes
  CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
  CMakeLists.txt
  README.md
  samples/Common.c
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/source/Ice/ConnectionListener.c
  src/source/Ice/ConnectionListener.h
Labels: enhancement, memory-optimization

#1934 Refactor TWCC
  .github/workflows/ci.yml
  README.md
  samples/Common.c
  src/source/PeerConnection/PeerConnection.c
  src/source/PeerConnection/PeerConnection.h
  src/source/PeerConnection/Rtcp.c
  src/source/PeerConnection/SessionDescription.h
  tst/RtcpFunctionalityTest.cpp
Labels: enhancement, memory-optimization

#1951 Add videoscale and videorate
  samples/kvsWebRTCClientMasterGstSample.c
Labels: GStreamer, Samples

#1955 New unit tests
  CMakeLists.txt
  src/source/Ice/IceAgentStateMachine.c
  src/source/Ice/NatBehaviorDiscovery.c
  src/source/Ice/SocketConnection.c
  src/source/Include_i.h
  src/source/Metrics/Metrics.c
  src/source/PeerConnection/DataChannel.c
  src/source/PeerConnection/Rtcp.c
  src/source/PeerConnection/Rtcp.h
  src/source/PeerConnection/Rtp.c
  src/source/Sdp/Deserialize.c
  src/source/Sdp/Serialize.c
  src/source/Signaling/FileCache.h
  tst/CMakeLists.txt
  tst/CryptoApiTest.cpp
  tst/IceApiTest.cpp
  tst/JitterBufferFunctionalityTest.cpp
  tst/MetricsApiTest.cpp
  tst/MetricsFunctionalityTest.cpp
  tst/NatBehaviorTest.cpp
  tst/PeerConnectionFunctionalityTest.cpp
  tst/RollingBufferFunctionalityTest.cpp
  tst/RtcpFunctionalityTest.cpp
  tst/RtpFunctionalityTest.cpp
  tst/SdpApiTest.cpp
  tst/SignalingApiTest.cpp
  tst/StunApiTest.cpp
Labels: Tests
