Repository awslabs/amazon-kinesis-video-streams-webrtc-sdk-c, pull requests merged in 2025-05, with the labels that each got.

#2118 Configure LWS logs with KVS log level
  src/source/Signaling/LwsApiCalls.c
  src/source/Signaling/LwsApiCalls.h
  src/source/Signaling/Signaling.c
Labels: enhancement, v1.13.0

#2120 Allow branches named with pattern 'test-pr-*' to trigger the CI
  .github/workflows/ci.yml
  .github/workflows/clang-format.yaml
  .github/workflows/codecov.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cross-compilation.yml
  .github/workflows/doxygen-gh-pages.yml
  .github/workflows/samples.yaml
  .github/workflows/sanitizers.yaml
Labels: CI, v1.13.0

#2126 Increase the signaling message receive buffer size
  CMakeLists.txt
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/source/Signaling/LwsApiCalls.c
  src/source/Signaling/Signaling.c
Labels: v1.12.1

#2128 Release v1.12.1
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/clang-format.yaml
  .github/workflows/codecov.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cross-compilation.yml
  .github/workflows/doxygen-gh-pages.yml
  .github/workflows/samples.yaml
  .github/workflows/sanitizers.yaml
  CMake/Dependencies/libawscpp-CMakeLists.txt
  CMake/Dependencies/libgtest-CMakeLists.txt
  CMake/Dependencies/libkvsCommonLws-CMakeLists.txt
  CMake/Dependencies/libmbedtls-CMakeLists.txt
  CMake/Dependencies/libopenssl-CMakeLists.txt
  CMake/Dependencies/libsrtp-CMakeLists.txt
  CMake/Dependencies/libusrsctp-CMakeLists.txt
  CMake/Dependencies/libwebsockets-CMakeLists.txt
  CMakeLists.txt
  README.md
  samples/h265SampleFrames/frame-0251.h265
  samples/h265SampleFrames/frame-0501.h265
  samples/h265SampleFrames/frame-0751.h265
  samples/h265SampleFrames/frame-1001.h265
  samples/h265SampleFrames/frame-1251.h265
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/source/Ice/NatBehaviorDiscovery.c
  src/source/PeerConnection/PeerConnection.c
  src/source/PeerConnection/Rtcp.c
  src/source/Signaling/LwsApiCalls.c
  src/source/Signaling/LwsApiCalls.h
  src/source/Signaling/Signaling.c
  tst/RtcpFunctionalityTest.cpp
  tst/main.cpp
Labels: Release, v1.12.1

#2125 Skip hostname parsing for stun servers
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/source/Ice/Network.c
Labels: bug, v1.13.0

#2138 Fix H265 FMTP issue with kvsWebrtcClientViewer
  src/source/PeerConnection/SessionDescription.h
Labels: bug, v1.13.0, viewer

#2135 Adjust the constant used to read the sample frames
  samples/kvsWebRTCClientMaster.c
Labels: Samples, v1.13.0

#2124 Add logs for socket creation fd
  src/source/Ice/IceUtils.c
  src/source/Ice/IceUtils.h
  src/source/Ice/SocketConnection.c
Labels: logging, v1.13.0

#2131 Fix undefined sanitizer reports for SDP
  src/source/PeerConnection/SessionDescription.c
Labels: v1.13.0, SDK

#2127 Enhance the ice config parser
  src/include/com/amazonaws/kinesis/video/webrtcclient/Include.h
  src/include/com/amazonaws/kinesis/video/webrtcclient/Stats.h
  src/source/Ice/IceUtils.h
  src/source/Signaling/LwsApiCalls.c
  src/source/Signaling/LwsApiCalls.h
  tst/IceConfigParsingTest.cpp
Labels: bug, Tests, v1.13.0
